server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: dev
      module: /about
      keyword: access
      __path__: /var/log/nginx/access.log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: staging
      module: /about
      keyword: access
      __path__: /var/log/nginx/access.log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: prod
      module: /about
      keyword: access
      __path__: /var/log/nginx/access.log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: dev
      module: none
      keyword: error
      __path__: /var/log/nginx/error.log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: staging
      module: none
      keyword: error
      __path__: /var/log/nginx/error.log

  - targets:
      - localhost
    labels:
      job: nginxlogs
      env: prod
      module: none
      keyword: error
      __path__: /var/log/nginx/error.log

  pipeline_stages:

  - regex:
      expression: '\"(?P<method>GET|POST|PUT|DELETE) (?P<endpoint>/[a-zA-Z0-9_/]*) HTTP.*\" (?P<status>[0-9]{3})'

  - labels:
      method:
      endpoint:
      status:
